name: check
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-14]
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v12
        with:
          name: cspr
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: System Info
        run: |
          uname -a
          nix --version

      - name: format
        if: matrix.os == 'ubuntu-latest'
        run: nix build -L --no-link --show-trace .#checks.x86_64-linux.format

      - name: casper-node (x86_64-linux)
        if: matrix.os == 'ubuntu-latest'
        run: nix build -L --no-link --show-trace .#packages.x86_64-linux.casper-node

      - name: casper-node (x86_64-darwin)
        if: matrix.os == 'macos-latest'
        run: nix build -L --no-link --show-trace .#packages.x86_64-darwin.casper-node

      - name: casper-node aarch64-darwin
        if: matrix.os == 'macos-14'
        run: nix build -L --no-link --show-trace .#packages.aarch64-darwin.casper-node

      - name: casper-node-launcher (x86_64-linux)
        if: matrix.os == 'ubuntu-latest'
        run: nix build -L --no-link --show-trace .#packages.x86_64-linux.casper-node-launcher

      - name: casper-node-launcher (x86_64-darwin)
        if: matrix.os == 'macos-latest'
        run: nix build -L --no-link --show-trace .#packages.x86_64-darwin.casper-node-launcher

      - name: casper-node-launcher (aarch64-darwin)
        if: matrix.os == 'macos-14'
        run: nix build -L --no-link --show-trace .#packages.aarch64-darwin.casper-node-launcher

      - name: casper-client-rs (x86_64-linux)
        if: matrix.os == 'ubuntu-latest'
        run: nix build -L --no-link --show-trace .#packages.x86_64-linux.casper-client-rs

      - name: casper-client-rs (x86_64-darwin)
        if: matrix.os == 'macos-latest'
        run: nix build -L --no-link --show-trace .#packages.x86_64-darwin.casper-client-rs

      - name: casper-client-rs (aarch64-darwin)
        if: matrix.os == 'macos-14'
        run: nix build -L --no-link --show-trace .#packages.aarch64-darwin.casper-client-rs

      - name: casper-node-contracts (x86_64-linux)
        if: matrix.os == 'ubuntu-latest'
        run: nix build -L --no-link --show-trace .#packages.x86_64-linux.casper-node-contracts

      - name: casper-node-contracts (x86_64-darwin)
        if: matrix.os == 'macos-latest'
        run: nix build -L --no-link --show-trace .#packages.x86_64-darwin.casper-node-contracts

      - name: casper-node-contracts (aarch64-darwin)
        if: matrix.os == 'macos-14'
        run: nix build -L --no-link --show-trace .#packages.aarch64-darwin.casper-node-contracts
